### ISSUE TITLE
Some programs malformed due to soloist parsing

### ISSUE THREAD

**Issue by mjbrodsky** [nyphilarchive/PerformanceHistory#2] opened 2015-03-02 23:13 UTC
Several programs (have yet to verify all affected IDs, but usually dance STA programs) are not being parsed properly because some soloists do not have roles assigned in the original data. This is messing up the parser that reformats the XML to nest soloist nodes inside a work node.

For example, see programID 12666.

**Comment by hrecht** [comment] 2015-08-09 18:08
A few of the other programs with this issue: programID 11107, 11913, 12237. This issue appears to have been fixed in [9030b13cbfceee6191bdaf6bccffb977729c0f9e](https://github.com/nyphilarchive/PerformanceHistory/commit/9030b13cbfceee6191bdaf6bccffb977729c0f9e) - no parse errors with that data - and reemerged with later data updates.

**Comment by eamonnbell** [comment] 2015-09-12 21:53
Also programID 11185

There has been a regression since [9030b13c](https://github.com/nyphilarchive/PerformanceHistory/commit/9030b13cbfceee6191bdaf6bccffb977729c0f9e)

The regression was introduced in [8580768f](https://github.com/nyphilarchive/PerformanceHistory/commit/8580768f1023731cbb96c3c5d759e9f855e2527c)

**Closed as completed** 2015-09-22 17:49 UTC
